kc_security:
    resource: "@KCSecurityBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
#base:
#  resource: "@AppBundle/Controller/"
#  type:     annotation


